### PR TITLE
added scala-arm to automatically close resources

### PR DESCRIPTION
**Pull request by jo-pol**
fixes EASY dependencies
#### When applied it will
- allow sub projects to omit a version number for scala-arm
#### How should this be manually tested?
- `mvn clean install` of easy-build with component versions listed below
#### related pull requests on github

| repo | PR | note |
| --- | --- | --- |
| easy-ingest | [#47](https://github.com/DANS-KNAW/easy-ingest/pull/47) | depends on this change |
| easy-bag-store | [#4](https://github.com/DANS-KNAW/easy-bag-store/pull/4) | idem |
|  |  | more will follow |

### CODE REVIEW

**Comment by jo-pol** [comment]
The build of easy-ingest failed because it depends on a change in dans-prototype.

**Comment by janvanmansum** [comment]
Please, also increment the version of `dans-prototype`.

**Comment by janvanmansum** [comment]
Also change it in `dans-java-prototype` and `dans-scala-prototype`.

**Comment by rvanheest** [comment]
@janvanmansum don't you need to change the version numbers in all other modules as well?

**Comment by janvanmansum** [comment]
That's right, if you want them to inherit the `scala-arm` configuration.

**Comment by rvanheest** [comment]
good you mention that
I'll change my PR asap

**Pull request merged**
