### PR TITLE
Refactoring of parent projects

### PR DESCRIPTION
**Pull request by janvanmansum**
The parent project `dans-prototype` now has two children: `dans-scala-prototype` and `dans-java-prototype`. Most of the stuff is still in the parent though. Including the scala library and scala maven plugin is no longer necessary when setting `dans-scala-prototype` as the parent. Also moved a lot of plug-in configuration to the parents.

The GitHub EASY projects have been modified to use these new parents (which are also accessible through https://easy.dans.knaw.nl/maven, so that Travis or other third parties may find them).

### CODE REVIEW

**Comment by janvanmansum** [comment]
@GeorgiKhomeriki @jo-pol @PaulBoon @ekoi @vesaakerman please have a look.

**Comment by jo-pol** [comment]
Shouldn't .iml files be ignored as they are created by Intellij?

**Comment by janvanmansum** [comment]
@jo-pol : Indeed, will add to .gitignore

**Comment by jo-pol** [comment]
I see three different language levels. Is there some logic behind it?

```
"NewModuleRootManager" LANGUAGE_LEVEL="JDK_1_5"
```

**Comment by janvanmansum** [comment]
@jo-pol : no, but the .iml-files will be removed anyway, or do you see a similar problem in the poms?

**Comment by jo-pol** [comment]
Sorry, overlooked it was only in iml files.

**Pull request merged**
